---
title: Efficient Aviation
sector:
- sectors::transportation
project_drawdown_url: https://www.drawdown.org/solutions/efficient-aviation
updated_by: d2e48869-19c6-464f-86b8-dbe8bc98ac04
updated_at: 1586100126
blueprint: solution
