---
title: Managed Grazing
sector:
- sectors::land-sinks
project_drawdown_url: https://www.drawdown.org/solutions/managed-grazing
updated_by: d2e48869-19c6-464f-86b8-dbe8bc98ac04
updated_at: 1586100126
blueprint: solution
