---
title: Refrigerant Management
sector:
- sectors::industry-buildings
project_drawdown_url: https://www.drawdown.org/solutions/refrigerant-management
updated_by: d2e48869-19c6-464f-86b8-dbe8bc98ac04
updated_at: 1586100126
blueprint: solution
